
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/pixiv?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: a474711475
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.30.129
    port: 6379

  mail:
      host: smtp.qq.com
      username: 921780541@qq.com
      password: inrdusflantnbdfb
      protocol: smtp
      properties.mail.smtp.auth: true
      properties.mail.smtp.port: 465
      properties.mail.display.sendmail: Javen
      properties.mail.display.sendname: Spring Boot Guide Email
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8
server:
  port: 8085
