spring:
  application:
    name: imgdetail
  datasource:
    url: jdbc:mysql://localhost:3306/pixiv?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: a474711475
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082
