fdfs:
   soTimeout: 1500
   connectTimeout: 600
   tracker-list: 192.168.30.129:22122
   thumb-image:             #缩略图生成参数
     width: 150
     height: 150



spring:
  application:
    name: manager
  datasource:
    url: jdbc:mysql://localhost:3306/pixiv?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: a474711475
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 20MB
  redis:
    host: 192.168.30.129
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activemq:
      user: admin
      password: admin
      broker-url: tcp://192.168.30.129:61616
      in-memory: false
      pool:
       enabled: true
       max-connections: 50
      packages:
       trust-all: true
  jms:
     pub-sub-domain: false



server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/
