server:
  port: 8079

jwt:
  key: Miuna
  ttl: 10800000

security:
  imageRole: roles[Image]
  userRole: roles[User]
  securityRole: roles[Miuna]


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: a474711475
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.30.129
    port: 6379
    timeout: 500
  application:
    name: authority




eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/


